# Generated by Django 4.0.3 on 2022-03-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_profilepic_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='image',
            field=models.ImageField(default='accounts/default.jpg', upload_to='accounts'),
        ),
    ]
