# Generated by Django 4.0.3 on 2022-03-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_profilepic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory_size',
            field=models.IntegerField(default=0),
        ),
    ]
